#!/bin/bash

# Remove existing symbolic link if it exists
if [ -L /data/web_static/current ]; then
    sudo rm /data/web_static/current
fi

# Create directory if it doesn't exist
sudo mkdir -p /data/web_static/current

# Create new symbolic link
sudo ln -s /data/web_static/releases/test/ /data/web_static/current
